protected/controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\ActiveRecord;
use app\models\Admin;
use app\models\Report;
use \Yii;
use yii\bootstrap\Html;
use yii\filters\AccessControl;
use app\models\Patient;
use app\models\LoginForm;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;

class AdminController extends BaseController {

	public function behaviors() {
		return [
			'access' => [
				'class'        => AccessControl::className(),
				'rules'        => [
					[
						'actions' => ['login', 'logout', 'error'],
						'allow'   => true,
					],
					[
						'allow' => true,
						'roles' => [Admin::ROLE],
					],
				],
				'denyCallback' => function ($rule, $action) {
					/** @var Patient $user */
					$user = Yii::$app->user->getIdentity();
					if ($user && $user->role != Admin::ROLE) {
						throw new HttpException(403, 'You are not allowed to perform this action');
					}
					/** @var \yii\base\InlineAction $action */
					return $this->redirect(['login']);
				},
			],
		];
	}

	public function actionIndex() {
		return $this->redirect(['patient-list']);
	}

	public function actionPatientList() {
		$models = Patient::find()->all();
		return $this->render('patient-list', [
			'models' => $models,
		]);
	}

	public function actionPatientAdd() {
		$model = new Patient();

		if (Yii::$app->request->isPost) {
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				return $this->redirect(['patient-list']);
			}
		}

		return $this->render('patient-edit', [
			'model' => $model,
		]);
	}

	public function actionPatientEdit($id) {
		$model = Patient::findOne($id);

		if (Yii::$app->request->isPost) {
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				return $this->redirect(['patient-list']);
			}
		}

		return $this->render('patient-edit', [
			'model' => $model,
		]);
	}

	/**
	 * Send link with auth key to user email
	 *
	 * @param int $id
	 */
	public function actionPatientSendAuthKey($id) {
		$model   = Patient::findOne($id);
		$authKey = $model->generateAuthKey();

		$body = Html::a('Link to log in', ['main/login-by-auth-key', 'token' => $authKey]);
		$sent = Yii::$app->mailer
			->compose()
			->setTextBody($body)
			->setFrom('no-reply@lab.test')
			->setTo($model->email)
			->setSubject('Link for log in')
			->send();
		Yii::$app->session->setFlash('sendAuthKey', $sent);
		$this->goBack();
	}

	public function actionReportList() {
		$models = Report::find()->all();
		return $this->render('report-list', [
			'models' => $models,
		]);
	}

	public function actionReportAdd() {
		$model = new Report();

		if (Yii::$app->request->isPost) {
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				return $this->redirect(['report-list']);
			}
		}

		return $this->render('report-edit', [
			'model'    => $model,
			'patients' => ArrayHelper::map(Patient::find()->all(), 'id', 'username'),
		]);
	}

	public function actionReportEdit($id) {
		$model = Report::findOne($id);

		if (Yii::$app->request->isPost) {
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				return $this->redirect(['report-list']);
			}
		}

		return $this->render('report-edit', [
			'model'    => $model,
			'patients' => ArrayHelper::map(Patient::find()->all(), 'id', 'username'),
		]);
	}

	/**
	 * Common delete action
	 *
	 * @param int         $id
	 * @param null|string $model Fully qualified class name for model to delete. 'Patient' by default
	 * @throws HttpException
	 */
	public function actionDelete($id, $model = null) {
		if (!$model) {
			$model = Patient::className();
		}

		/** @var ActiveRecord $model */
		$model = $model::findOne($id);
		if (!$model) {
			throw new HttpException(404, "Model #{$id} not found");
		}

		$model->delete();
		$this->goBack();
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm(['scenario' => LoginForm::SCENARIO_ADMIN]);
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('/main/login', [
				'model' => $model,
			]);
		}
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Admin;
use app\models\Report;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\Patient;
use yii\web\HttpException;

class MainController extends BaseController {

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'login-by-auth-key', 'logout', 'error'],
						'allow'   => true,
					],
					[
						'actions' => ['index'],
						'allow'   => true,
						'roles'   => ['@'],
					],
					[
						'allow' => true,
						'roles' => [Patient::ROLE],
					],
				],
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->getIdentity()->role == Admin::ROLE) {
			return $this->redirect(['admin/index']);
		}

		/** @var Patient $patient */
		$patient = Yii::$app->user->getIdentity();
		return $this->render('index', [
			'models' => $patient->reports,
		]);
	}

	public function actionReportDetail($id) {
		$report = Report::findOne($id);
		if (!$report) {
			throw new HttpException(404, 'Report not found');
		}

		return $this->render('report-detail', [
			'model' => $report,
		]);
	}

	public function actionReportExport($id) {
		$report = Report::findOne($id);
		if (!$report) {
			throw new HttpException(404, 'Report not found');
		}

		$this->layout = false;
		/** @var \app\components\Pdf $pdf */
		$pdf = Yii::$app->pdf;
		$pdf->setHtml($this->render('report-as-pdf', [
			'model' => $report,
		]));

		$filename = date('Ymd') . "_report_{$id}.pdf";
		header('Content-type:application/pdf');
		header('Content-Disposition:attachment;filename=' . $filename);
		return $pdf->getOutput();
	}

	public function actionReportMail($id) {
		$report = Report::findOne($id);
		if (!$report) {
			throw new HttpException(404, 'Report not found');
		}

		$this->layout = false;
		/** @var \app\components\Pdf $pdf */
		$pdf = Yii::$app->pdf;
		$pdf->setHtml($this->render('report-as-pdf', [
			'model' => $report,
		]));
		$filename = date('Ymd') . "_report_{$id}.pdf";
		$sent     = Yii::$app->mailer
			->compose()
			->attachContent($pdf->getOutput(), ['fileName' => $filename, 'contentType' => 'application/pdf'])
			->setFrom('no-reply@lab.test')
			->setTo($report->patient->email)
			->setSubject("PDF attachment {$filename}")
			->send();
		Yii::$app->session->setFlash('sendReportPdf', $sent);
		$this->goHome();
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLoginByAuthKey($token) {
		Yii::$app->user->logout();

		$patient = Patient::findIdentityByAccessToken($token);
		if (!$patient) {
			throw new HttpException('Patient not found');
		}

		$model           = new LoginForm(['scenario' => LoginForm::SCENARIO_PATIENT_BY_TOKEN]);
		$model->username = $patient->username;
		$model->token    = $token;
		if (!$model->login()) {
			throw new Exception("Could not log in user: {$patient->username}");
		}
		$this->goBack();
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}
}

protected/views/layouts/main.php
<?php
use yii\helpers\Html;

use yii\bootstrap\Nav;
//use yii\bootstrap\NavBar;
use app\assets\AppAsset;
use app\models\Product;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

$action = Yii::$app->controller->action->id;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body style="padding-top: 15px">

<?php $this->beginBody() ?>
<?php if (!Yii::$app->user->isGuest) { ?>
	<div class="container">
		<div class="clearfix form-group">
			<div class="pull-right"><?= Yii::$app->user->getIdentity()->username ?>&nbsp;&nbsp;&nbsp;<a
					href="<?= Url::to(['main/logout']) ?>" class="btn btn-warning">Logout</a></div>
		</div>

		<?php
		$route = Yii::$app->controller->route;
		if (Yii::$app->user->getIdentity()->role == \app\models\Admin::ROLE) {
			$items = [
				[
					'label'  => 'Patients',
					'url'    => ['admin/patient-list'],
					'active' => in_array($route, ['admin/patient-list', 'admin/patient-add', 'admin/patient-edit']),
				],
				[
					'label'  => 'Reports',
					'url'    => ['admin/report-list'],
					'active' => in_array($route, ['admin/report-list', 'admin/report-add', 'admin/report-edit']),
				],
			];
		} else {
			$items = [
				[
					'label'  => 'User reports',
					'url'    => ['main/index'],
					'active' => in_array($route, ['main/index']),
				],
			];
		}
		echo Nav::widget([
			'options' => ['class' => 'nav-pills'],
			'items'   => $items,
		]);
		?>
	</div>
<?php } ?>
<div class="content">
	<div class="container">
		<h2 class="page-header"><?= $this->title ?></h2>
		<?= $content ?>
	</div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>